### ISSUE TITLE
Doesn't change color of the page

### ISSUE THREAD

**Issue by Uzwername** [kathrynmcbain/ExtensionTutorialFix#1]
I don't know if I'm using it wrong but when I visit any [developers.chrome.com](https://developers.chrome.com) page the extension icon lights up as expected (not instantly, but after I go to options page & return back, it does). I can also visit the options page & pick a colour.

Nevertheless, the picked colour is never actually applied to the background (the background always stays default white).

Os: macOS Catalina 10.15.5
Chrome: Version 84.0.4147.89 (Official Build) (64-bit)

If you want to have more info, I'd glad to provide it :)

---

Just updated to Chrome Version 84.0.4147.125 (Official Build) (64-bit), curiously enough, the icon doesn't light up anymore on [developers.chrome.com](https://developers.chrome.com) pages. I've tried to re-install it but it didn't help.

**Comment by kathrynmcbain** [comment]
Hi @Uzwername  

Thanks for raising this issue! 

This has brought an important point to my attention - Chrome are using both the subdomains of developer.chrome.com and developerS.chrome.com. My code is only set to fire on sites using developer.x - hence why I think the icon does not light up for you.

Could you confirm this is the case by removing the s from the url? If so, I will update the code accordingly with a pull request so that it works with both subdomains. 

Thanks again.

**Comment by Uzwername** [comment]
@kathrynmcbain Works perfectly on [developer.chrome.com](https://developer.chrome.com/) :)
